### PR TITLE
fix batch results removing superfluous commas.

### PR DESCRIPTION
**Pull request by artnim**
This is about the processing of requests and compiling of responses in batches. If the request batch consists of message calls and notifications the code in the current master appends a comma to each response, even if successor of the corresponding request ist a notification. If the last request in a batch is a notification, the response looks like this:
```
[{"jsonrpc...},]
```
Even if newtonsoft.json is able to parse such arrays, some other json-frameworks aren't.

By fixing this, I, remarked, that the code for the processing was duplicate (copy/paste). Even the handling of single and batch requests was duplicated.

Best Regards,

Martin

### CODE REVIEW

**Comment by Astn** [comment]
Great find!

**Comment by Astn** [comment]
The tests are running on this branch. Looks like you have forgotten to commit the project file for the test project. I'm getting this error:
Error	3	The type or namespace name 'Newtonsoft' could not be found (are you missing a using directive or an assembly reference?)	C:\Users\msdn_000\Source\Repos\JSON-RPC.NET\AustinHarris.JsonRpcTest\UnitTest1.cs	5	7	AustinHarris.JsonRpcTest

**Comment by artnim** [comment]
Of course, you're right. I'll fix that in a few minutes.

**Comment by artnim** [comment]
Now all the tests, except those three that previously failed, succeeds.

One question, how you're handling the line endings? Cause I'm encountering some crlf/lf issues...

**Comment by Astn** [comment]
I have core.autocrlf set to true. I'm seeing the line ending issues as well.

**Comment by Astn** [comment]
With your last commit I have 128 tests passing on my machine. Which ones are failing for you?

**Comment by Astn** [comment]
Oh, and the merge says it can't do it automatically because of conflicts. Can you please update with latest so this will be a clean merge.
Thanks for your help!

**Comment by artnim** [comment]
Give me just five minutes. I'm in the middle of rebasing it...

**Comment by Astn** [comment]
No rush, I'm climbing into bed right now. Early morning. I'll pickup again tomorrow.

**Comment by artnim** [comment]
Good night!
The branch is now rebased on your merge of PR #32.

**Comment by Astn** [comment]
Looking pretty good!

**Pull request merged**
